### ISSUE TITLE
How can I import my MD5 hash

### ISSUE THREAD

**Issue by 687766616e** [alainesp/HashSuiteDroid#1]
How can I import my MD5 hash
I tried to put MD5 directly in a ".txt" file.
But the import failed 
(My MD5 is 32 digits

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by alainesp** [comment]
Hi Huitc.

On Mar 25, 2018 6:43 AM, "huitc" <notifications@github.com> wrote:

How can I import my MD5 hash
I tried to put MD5 directly in a ".txt" file.
But the import failed

You need to put a fake username first. Something like:

User:<md5_hash>

Hope this helps,
Alain
