### ISSUE TITLE
Availability on F-Droid

### ISSUE THREAD

**Issue by supermamie** [alainesp/HashSuiteDroid#3]
Is it possible to add HashSuite to F-Droid ?
Here is the submission tracker : https://gitlab.com/fdroid/rfp

I know there is already a direct download link, but a build from F-Droid is a security that roves the apk is really builded from the provided source.

Thanks

**Comment by K12609** [comment]
Add HashSuit to F-Droid https://gitlab.com/fdroid/rfp
