### ISSUE TITLE
Facebook Msgr

### ISSUE THREAD

**Issue by Redogricki** [alainesp/HashSuiteDroid#5]
Looking for password to facebook accnt https://www.facebook.com/blade.jax.90

Blade.jax.90@gmail.com
Rickisdaddy70@gmail.com
Rickisdaddy84@gmail.com
Lilmexico888@gmail.com

**Comment by alainesp** [comment]
Hash Suite can't be used to recover online service (like Facebook) passwords. Your best bet is to contact the service support and explain to them your situation.
