### ISSUE TITLE
Loading dictionaries in the application does not work.

### ISSUE THREAD

**Issue by xb3b6** [alainesp/HashSuiteDroid#6]
HSD v1.5.1.
After choosing to download the dictionary, nothing happens, the dictionary also disappears from the download list.

Android 10.

**Comment by alainesp** [comment]
This is intended behavior. The dictionary should be downloaded, remove from the download list, and added to the wordlist list. To see this list tap the "Params" tab and then "Wordlist file".

**Comment by xb3b6** [comment]
The dictionary is not downloaded, it disappears from the download list and it is not on the parameters tab.  This is mistake.

**Comment by xb3b6** [comment]
![bug](https://user-images.githubusercontent.com/80679015/133368510-d538f5a2-655f-42b6-b317-61e4c6789a97.gif)
@alainesp
