### ISSUE TITLE
No hashes loaded...

### ISSUE THREAD

**Issue by CamsShaft** [alainesp/HashSuiteDroid#7]
Hi there :) hope I can get a hand here. I try to import some hashes and it says no hashes loaded and also no users added. Not sure how to get around this because the website isn't very helpful either. Positive I just can't think straight at the moment. Thanks for anything. 
![Screenshot_20231001_182947_Hash Suite Droid](https://github.com/alainesp/HashSuiteDroid/assets/141678661/fd4dffe1-d1a6-4360-b688-9e17a6b38cef)

**Comment by alainesp** [comment]
> Hi there :) hope I can get a hand here. I try to import some hashes and it says no hashes loaded and also no users added. Not sure how to get around this because the website isn't very helpful either. Positive I just can't think straight at the moment. Thanks for anything. ![Screenshot_20231001_182947_Hash Suite Droid](https://user-images.githubusercontent.com/141678661/271865781-fd4dffe1-d1a6-4360-b688-9e17a6b38cef.png)

Hi. It appears you imported a WPA-PSK hash that already exists on the app (see the Exist column).
