### ISSUE TITLE
Not compatible with some Xiaomi

### ISSUE THREAD

**Issue by lucaselblanc** [alainesp/HashSuiteDroid#9]
I tested it on two different Xiaomi models, one of them was the Redmi Note 9s (SDK 31) and the other was the Redmi Note 10s (SDK 33), and the playstore says that the app is not compatible with any of these models, perhaps due to from the SDK?

**Comment by alainesp** [comment]
We tested Hash Suite Droid on a Xiaomi with Android 11 and it works without problem. We are not sure what the problem may be.

**Comment by lucaselblanc** [comment]
> We tested Hash Suite Droid on a Xiaomi with Android 11 and it works without problem. We are not sure what the problem may be.

I used reverse engineering to look at the apk files, and the target SDK is 30, this information is available in AndroidManifest.xml, it will not work well from Android 12 onwards (SDKs 31,32,33,34)

**Comment by alainesp** [comment]
This project is open-source so you don't need to reverse engineer the app, you can take a look at the code here on GitHub. We will try to update the target SDK for the next version of the app.

**Comment by lucaselblanc** [comment]
> This project is open-source so you don't need to reverse engineer the app, you can take a look at the code here on GitHub. We will try to update the target SDK for the next version of the app.

I could have done that, but I had my MT Manager open and decided to look there haha, thanks for wanting to update the SDK for the next update, by the way, I have a similar app on the Playstore, it's called: "Data Leak Search Hash Cracker", I developed it as a cyber-security toolkit, and it has a hash cracking tool in the formats: md5, sha1 and sha256, and I intend to bring new formats like LM or NTLM soon, currently the generation of hashes per second is tied to the device's FPS, I haven't figured out how to get around this problem yet, as it is between 60 and 120 hashes per second.
